# Generated by Django 3.0.6 on 2021-05-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_activity_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('F', 'Favorite'), ('L', 'Like'), ('U', 'Up Vote'), ('D', 'Down Vote')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('F', 'Favorited'), ('A', 'Answered'), ('W', 'Accepted Answer')], max_length=1),
        ),
    ]
