# Generated by Django 3.0.6 on 2021-06-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0007_auto_20210611_1159'),
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='group_admins', to='webuser.UserInfo'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webuser.UserInfo'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='webuser.UserInfo'),
        ),
    ]
