# Generated by Django 3.0.6 on 2021-06-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.IntegerField()),
                ('name', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorFilmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('film_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='filminfo',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='film_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='genres',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='issue',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='runtime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='filminfo',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
