# Generated by Django 3.0.6 on 2021-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210511_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(blank=True, max_length=80)),
                ('genres', models.CharField(blank=True, max_length=50)),
                ('issue', models.DateTimeField()),
                ('runtime', models.TimeField()),
                ('summary', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('comment_count', models.IntegerField(blank=True)),
                ('rate', models.FloatField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='full/')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('film_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('comment_time', models.DateTimeField(null=True)),
                ('comment_adopt', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='moviecoment',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviecoment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moviehistory',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='moviehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='MovieSpider',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='MovieComent',
        ),
        migrations.DeleteModel(
            name='MovieHistory',
        ),
    ]
