# Generated by Django 3.0.6 on 2021-06-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
