# Generated by Django 3.0.6 on 2021-06-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('key', models.CharField(max_length=20)),
            ],
        ),
    ]
