# Generated by Django 3.0.6 on 2021-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0006_remove_webuser_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('key', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='webuser',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='webuser',
            name='user',
        ),
    ]
