# Generated by Django 3.0.6 on 2021-06-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0002_auto_20210611_1159'),
        ('webuser', '0007_auto_20210611_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Webuser',
        ),
    ]
